version: "3"

services:
  # 查询的前端页面
  ui:
    image: jaegertracing/jaeger-query:1.37.0
    container_name: ui
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://es:9200
      # - ES_USERNAME=elastic
      # - ES_PASSWORD=
      # - JAEGER_AGENT_PORT=6831
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    ports:
      - 16685:16685
      # 前端页面端口
      - 16686:16686
      - 16687:16687
    restart: unless-stopped

  # 数据收集
  collector:
    image: jaegertracing/jaeger-collector:1.37.0
    container_name: collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://es:9200
      # - ES_USERNAME=elastic
      # - ES_PASSWORD=
    ports:
      - 14250:14250 # grpc
      # - 14268:14268 # http
      - 14269:14269
    restart: unless-stopped
  
  # 数据收集处理
  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    ports:
      - 4317:4317
      - 4318:4318
      - 6831:6831
      - 14268:14268
      - 8889:8889
    command: --config /etc/otelcol/otel-collector-config.yml
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  es:
    image: elasticsearch:7.17.3
    container_name: es
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped
  
  # 生成模拟的trace数据
  hotrod:
    image: jaegertracing/example-hotrod:latest
    container_name: hotrod
    environment:
      - JAEGER_AGENT_HOST=otel_collector
      - JAEGER_AGENT_PORT=6831
    ports:
      - 8080-8083:8080-8083
    restart: unless-stopped

  # 生成模拟的trace数据
  microsim:
    image: yurishkuro/microsim:0.2.0
    command: "-j http://otel_collector:14268/api/traces -d 24h -s 500ms"
    restart: unless-stopped